[General]
UITheme=theme-contrast-dark
appdata="@ByteArray(eyJ1c2VybmFtZSI6ImV4eGVkbGlnaHQiLCJkb2NvcGVubW9kZSI6ImVkaXQiLCJyZXN0YXJ0Ijp0cnVlLCJsYW5naWQiOiJlbi1VUyIsInVpc2NhbGluZyI6IjEwMCIsInVpdGhlbWUiOiJ0aGVtZS1jb250cmFzdC1kYXJrIiwiZWRpdG9yd2luZG93bW9kZSI6ZmFsc2UsInNwZWxsY2hlY2tkZXRlY3QiOiJhdXRvIiwidXNlZ3B1IjpmYWxzZSwidXNlYWkiOmZhbHNlfQ==)"
editorWindowMode=false
ignoreMsgAboutOpenTabs=true
openPath=/home/exxedlight/\x420\x430\x431\x43e\x447\x438\x439 \x441\x442\x43e\x43b
position=@Rect(5 29 1910 1022)
titlebar=custom

[EditorsGeometry]
0\position=@Rect(5 29 1910 1022)
