[General]
AlwaysUseExifThumb=false
DuplicateHistogramProximity=60
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a}\0\0\x4\x1d\0\0\0\0\0\0\0\0\0\0\a}\0\0\x4\x1d\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\a}\0\0\x4\x1d)
ImageToolActions=prevImage, nextImage, firstImage, lastImage, toggleSlideShow, |, save, saveAs, moveToTrash, delete, |, zoomIn, zoomOut, resetZoom, origZoom, rotateRight, rotateLeft, rotateMouse, flipH, flipV, |, resize, crop, blackout, cartouche, annotate, colors
WallpaperCommand=
WindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x2\0\0\0\0\0\0\0\xa2\0\0\x3\xee\xfc\x2\0\0\0\x3\xfb\0\0\0\x12\0T\0h\0u\0m\0\x62\0V\0i\0\x65\0w\x1\0\0\0\x30\0\0\x3\xee\0\0\0M\0\xff\xff\xff\xfb\0\0\0\x16\0\x46\0i\0l\0\x65\0 \0S\0y\0s\0t\0\x65\0m\b\0\0\0\x32\0\0\x3\xd0\0\0\0M\0\xff\xff\xff\xfb\0\0\0\x12\0\x42\0o\0o\0k\0m\0\x61\0r\0k\0s\b\0\0\x2\x36\0\0\x1\xcc\0\0\0M\0\xff\xff\xff\0\0\0\x1\0\0\0\xd3\0\0\x3\xd0\xfc\x2\0\0\0\x2\xfb\0\0\0\x18\0I\0m\0\x61\0g\0\x65\0P\0r\0\x65\0v\0i\0\x65\0w\0\0\0\0\x32\0\0\x3\xa9\0\0\0\x17\0\xff\xff\xff\xfc\0\0\x2-\0\0\x1\xd5\0\0\0\0\0\xff\xff\xff\xfc\x1\0\0\0\x2\xfb\0\0\0\b\0T\0\x61\0g\0s\b\0\0\x5L\0\0\0\x85\0\0\0\x8b\0\xff\xff\xff\xfb\0\0\0\x14\0I\0m\0\x61\0g\0\x65\0 \0I\0n\0\x66\0o\x2\0\0\x5L\0\0\x2-\0\0\x2*\0\0\x1\xd5\0\0\x6\xd6\0\0\x3\xee\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\xe\0M\0\x61\0i\0n\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
bookmarksDockVisible=false
defaultSaveQuality=90
deleteConfirm=false
enableAnimations=true
exifRotationEnabled=true
exifThumbRotationEnabled=true
fileSystemDockVisible=false
hideDockTitlebars=false
imageInfoDockVisible=false
imagePreviewDockVisible=false
lastDir=
optionFullScreenMode=false
optionShowImageName=true
optionThumbsBackgroundColor=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
optionThumbsLayout=0
optionThumbsPagesReadCount=2
optionThumbsSortFlags=0
optionThumbsTextColor=@Variant(\0\0\0\x43\x1\xff\xff\xfa\xfa\xfa\xfa\xfa\xfa\0\0)
optionThumbsZoomLevel=150
optionViewerBackgroundColor=@Variant(\0\0\0\x43\x1\xff\xff\x11\xeb\x11\xeb\x11\xeb\0\0)
reverseMouseBehavior=false
scrollZooms=true
setWindowIcon=false
showHiddenFiles=false
showViewerToolbar=false
slideShowCrossfade=true
slideShowDelay=5
slideShowRandom=false
smallToolbarIcons=true
specifiedStartDir=
startupDir=1
tagsDockVisible=false
thumbViewDockVisible=true
thumbsBackgroundImage=
upscalePreview=false
wrapImageList=false

[CopyMoveToPaths]
path1=/home/exxedlight

[Shortcuts]
about=
addBookmark=
annotate=
batchTransform=
blackout=
cartouche=
chooseApp=
closeImage=Esc
colors=Ctrl+O
copy=Ctrl+Shift+C
copyImage=Ctrl+C
copyTo=Ctrl+Y
createDir=
crop=
cut=Ctrl+X
delete=Shift+Del
exit=Ctrl+Q
filterImagesFocus=Ctrl+F
findDupes=
firstImage=Home
flipH=H
flipV=V
freeRotateLeft=Ctrl+Shift+Left
freeRotateRight=Ctrl+Shift+Right
fullScreen=F11
goBack=Alt+Left
goFrwd=Alt+Right
goHome=
imageinfo=Ctrl+I
includeSubDirs=
invertSelection=
keepTransform=Ctrl+K
keepZoom=
lastImage=End
letterbox=Ctrl+G
lockDocks=Ctrl+M
moveDown=Down
moveLeft=
moveRight=
moveTo=
moveToTrash=Del
moveUp=Up
nextImage=Right
open=Return
openWithMenu=
origZoom=1
paste=Ctrl+V
pasteImage=Ctrl+Shift+V
prevImage=Left
randomImage=Ctrl+D
refresh=F5
regenerateThumbnail=
removeBookmark=
removeMetadata=
rename=F2
resetZoom=*
resize=
rotateLeft=L
rotateMouse=
rotateRight=R
save=Ctrl+S
saveAs=
selectAll=
setClassicThumbs=
setCompactThumbs=
setPathFocus=Ctrl+L
setSaveDir=
setSquareThumbs=
settings=Ctrl+P
setwallpaper=
showClipboard=
showHidden=Ctrl+H
showViewerToolbar=T
showgrid=G
smallToolbarIcons=
sortByBrightness=
sortByColor=
sortByExifTime=
sortByName=
sortBySimilarity=
sortBySize=
sortByTime=
sortByType=
sortReverse=
thumbsGoBottom=Ctrl+End
thumbsGoTop=Ctrl+Home
thumbsZoomIn=
thumbsZoomOut=
toggleSlideShow=Ctrl+W
up=Alt+Up
zoomIn=+
zoomOut=-
