shift+s         screenshot each-frame
f               frame-step
s               frame-back-step
UP              add volume +5
DOWN            add volume -5
Alt+k           add video-rotate 90
Alt+l           add video-rotate -90