# Check the following link for mpv's default keybindings:
# https://github.com/mpv-player/mpv/blob/master/etc/input.conf

# --- BASE
SPACE           cycle pause
MBTN_RIGHT      cycle pause
LEFT            seek -5
RIGHT           seek 5



# --- FEATURES
f               frame-step
а               frame-step
d               frame-back-step
в               frame-back-step
n               cycle video-unscaled
C               cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"
c               script-binding cycle-visualizer


# --- SOUND
UP              add volume +2
DOWN            add volume -2
WHEEL_UP        add volume 2
WHEEL_DOWN      add volume -2
x               add audio-delay -0.05
X               add audio-delay +0.05

# --- ROTATE
Alt+k           add video-rotate 90
Alt+л           add video-rotate 90
Alt+l           add video-rotate -90
Alt+д           add video-rotate -90

# --- FLIP
h               vf toggle hflip
v               vf toggle vflip
р               vf toggle hflip
м               vf toggle vflip



# --- SCRIPTS   --------------------------------------------------
Ctrl+c          script-binding uosc/copy-to-clipboard
Ctrl+v          script-binding uosc/paste-to-playlist
tab             script-binding uosc/menu
b               script-binding set_gif_start            # set the start timestamp for to make GIF (mpv-gif.lua)
B               script-binding set_gif_end              # set the stop timestamp for to make GIF (mpv-gif.lua)
ctrl+b          script-binding make_gif                 # make the GIF using start and stop timestamps (mpv-gif.lua)
i               script-binding stats/display-stats
I               script-binding stats/display-stats-toggle



Ctrl+1          cycle-values glsl-shaders "" "~~/shaders/FSRCNNX/FSRCNNX_x2_16-0-4-1_enhance.glsl"